Translation for de-DE
Kedyn/fusliez-notes pull request #58
Opened 2020-10-09 20:54 UTC by Fabian9799

Added Translation for German

2020-10-10 01:08 UTC, I3lackRacer requested changes

2020-10-10 01:08 UTC, I3lackRacer commented on src/assets/locales/de/DE/translation.json
> +    "medBay": "MedBer",
'Krankenstation'

2020-10-10 01:08 UTC, I3lackRacer commented on src/assets/locales/de/DE/translation.json
> +    "innocentTextColor": "Textfarbe für unschuldige",
'Unschuldige' capitalization

2020-10-10 01:14 UTC, Kedyn commented
Thank you for your contribution, we are currently in the process of another big update to the UI, would you mind holding off for a bit until we get that done. Thank you in advance.

2020-10-11 18:03 UTC, Kedyn commented
@Fabian9799 I think we are done with all the new UI things we wanted to translate, so you are welcome to translate the new things as shown: https://github.com/Kedyn/fusliez-notes/tree/master/src/assets/locales

2020-10-11 18:52 UTC, Fabian9799 commented
Created newer version: [https://github.com/Kedyn/fusliez-notes/pull/67](https://github.com/Kedyn/fusliez-notes/pull/67)

2020-10-11 18:52 UTC, closed without merging