Add french translation
Kedyn/fusliez-notes pull request #95
Opened 2020-10-24 12:33 UTC by Coleyra

2020-10-24 15:50 UTC, MissingNoShiny commented on src/assets/locales/fr-FR/translation.json
> +    "crewmate": "Equipage",
```suggestion
    "crewmate": "Équipage",
```

2020-10-24 16:26 UTC, MissingNoShiny requested changes
Good translation overall. I fixed a few mistakes, missing accents and unnecessary capitalizations.

2020-10-24 16:26 UTC, MissingNoShiny commented on src/assets/locales/fr-FR/translation.json
> +    "unlockPlayers": "Dévérouiller les Joueurs"
```suggestion
    "crewmate": "Équipage",
    "impostor": "Imposteur",
    "resetScores": "Réinitialiser les scores",
    "resetRound": "Réinitialiser la partie",
    "resetAll": "Tout réinitialiser",
    "notes": "Notes",
    "resetNotes": "Réinitialiser les notes",
    "lockPlayers": "Verrouiller les joueurs",
    "unlockPlayers": "Déverrouiller les joueurs"
```

2020-10-24 16:26 UTC, MissingNoShiny commented on src/assets/locales/fr-FR/translation.json
> +    "electrical": "Electrique",
```suggestion
    "electrical": "Électrique",
```

2020-10-24 16:26 UTC, MissingNoShiny commented on src/assets/locales/fr-FR/translation.json
> +    "cafeteria": "Cafeteria",
```suggestion
    "cafeteria": "Cafétéria",
```

2020-10-24 16:26 UTC, MissingNoShiny commented on src/assets/locales/fr-FR/translation.json
> +    "launchpad": "Rampe de Lancement",
```suggestion
    "launchpad": "Rampe de lancement",
```

2020-10-24 16:26 UTC, MissingNoShiny commented on src/assets/locales/fr-FR/translation.json
> +    "about": "A propos",
```suggestion
    "about": "À propos",
```

2020-10-24 16:26 UTC, MissingNoShiny commented on src/assets/locales/fr-FR/translation.json
> +    "office": "Office",
```suggestion
    "office": "Bureau",
```

2020-10-24 16:26 UTC, MissingNoShiny commented on src/assets/locales/fr-FR/translation.json
> +    "uiSettings": "Réglages de l'Interface",
```suggestion
    "uiSettings": "Réglages de l'interface",
```

2020-10-24 16:26 UTC, MissingNoShiny commented on src/assets/locales/fr-FR/translation.json
> +    "resetPlayers": "Réinitialiser les Positions"
```suggestion
    "resetPlayers": "Réinitialiser les positions"
```

2020-10-24 16:26 UTC, MissingNoShiny commented on src/assets/locales/fr-FR/translation.json
> +    "lime": "Citron",
"Citron" by itself is a shade of yellow. I suggest either "Vert citron", "Vert clair", or if both of those don't fit, "Tilleul" (arguably not as good, but shorter).
```suggestion
    "lime": "Vert clair",
```

2020-10-24 16:26 UTC, MissingNoShiny commented on src/assets/locales/fr-FR/translation.json
> +    "dragInstructions": "Faites glisser les joueurs sur la carte pour les traquer",
```suggestion
    "dragInstructions": "Faites glisser les joueurs sur la carte pour suivre leur position",
```

2020-10-24 21:05 UTC, Kedyn approved these changes
Thank you for your contribution. Please keep in mind that we are working towards few new things and we might be adding/removing some things, so I ask if you would like to keep this translation up to date keep an eye as to what has been changed. I will be trying to open an issue mentioning you and all those who have helped with translations once we are ready to deploy our next version.

PS: Would you mind adding yourselves to the readme, thank you.

2020-10-25 13:56 UTC, MissingNoShiny commented
I wouldn't want to steal credit for this translation, as I barely changed anything of importance (and besides, I'm pretty new to contributing to repos that aren't mine, and I believe I don't have write access to this branch?). However, feel free to mention me if you need any further help!

2020-10-26 15:54 UTC, merged