Improved spanish translation.json
Kedyn/fusliez-notes pull request #96
Opened 2020-10-25 22:16 UTC by eduardovegar

Several words were google translations and not the correct Spanish word. Added "tildes" to all words that required them. Improved verb conjugations for tense consistency

Algunas palabras no tenían la traducción correcta al Español. He añadido tildes para todas las palabras que lo requerían. También mejoré las conjugaciones de los verbos.

2020-10-26 15:53 UTC, Kedyn requested changes
Antes que nada gracias por tu aportacion. He dejado algunas sugerencias que espero puedas revisar.

PS: I don't know if I should feel flattered about being compared to google translations or bad, either way thank you for contributing.

2020-10-26 15:53 UTC, Kedyn commented on src/assets/locales/es-MX/translation.json
> +    "pink": "Rosado",
Se que rosado es correcto, pero cuando digo rosado me suena mas a el estado de estar rosado que al color.
Creo que esta bien dejar Rosado, solo estoy dando mi razonamiento al por que rosa.

2020-10-26 15:53 UTC, Kedyn commented on src/assets/locales/es-MX/translation.json
> +    "lockPlayers": "Bloquear edición de jugadores",
En ingles hemos utilizado Lock Players, que literal seria Bloquear Jugadores, yo he puesto edicion porque se me hacia un poco mas correcto, puesto que estamos bloqueando a la edicion y no a los jugadores en si. La razon del por que no agregue jugadores es porque interfiere un poco con el diseño (creo que en movil). Creo que esto si requeriria una revision.

2020-10-26 15:53 UTC, Kedyn commented on src/assets/locales/es-MX/translation.json
> +    "unlockPlayers": "Desbloquear edición de jugadores"
Al igual que lo anterior, creo que esto tambien necesita una revision.

2020-10-26 15:53 UTC, Kedyn commented on src/assets/locales/es-MX/translation.json
> +    "admin": "Administración",
Administracion es un poco larga a comparacion del espacio asignado para la palabra en los mapas. Sugiero revertir este cambio.

2020-10-26 15:53 UTC, Kedyn commented on src/assets/locales/es-MX/translation.json
> +    "resetPlayers": "Reiniciar posiciones de jugadores"
Creo que el "de jugadores" es inecesario e puede que interrumpa el diseño/interfaz (no recuerdo probar esto).

2020-10-27 23:06 UTC, eduardovegar commented on src/assets/locales/es-MX/translation.json
> +    "pink": "Rosado",
Concuerdo, ambas opciones son correctas. Lo cambie a rosado porque pense tenia mas sentido con los demas colores; morado, rosado, en vez de purpura y rosa. Yo estaria de acuerdo con cualquier color que tu creas sea mejor

2020-10-27 23:09 UTC, eduardovegar commented on src/assets/locales/es-MX/translation.json
> +    "lockPlayers": "Bloquear edición de jugadores",
Entiendo. Mi traduccion era simplemente mas explicativa; dado que el boton no estaba cerca de los jugadores, podria confundirse que es lo que se bloqueaba.

2020-10-27 23:11 UTC, eduardovegar commented on src/assets/locales/es-MX/translation.json
> +    "unlockPlayers": "Desbloquear edición de jugadores"
Entendido. He revertido cambios

2020-10-27 23:12 UTC, eduardovegar commented on src/assets/locales/es-MX/translation.json
> +    "admin": "Administración",
Tiene sentido, aunque si no esta cortada la palabra se puede confundir con el ingles. Sugiero reducir a Admin. con el punto al final para indicar que la palabra esta recortada

2020-10-27 23:12 UTC, eduardovegar commented on src/assets/locales/es-MX/translation.json
> +    "resetPlayers": "Reiniciar posiciones de jugadores"
He revertido el cambio

2020-10-27 23:16 UTC, eduardovegar commented
I've made changes as suggested. For the pink word, it feels more natural to me to say "morado y rosado" than "morado y rosa" which is why I changed it. However both versions are correct so if you prefer "rosa" I will gladly change it.

Thanks for reviewing the changes !

2020-10-27 23:38 UTC, Kedyn approved these changes
Genial, pronto estare sacando la version 1.0.0, la cual tendra algunos cambios mas. Espero poder contar con tu ayuda para traducir estos cambios de ante mano gracias.

2020-10-27 23:38 UTC, merged

2020-11-27 00:50 UTC, Kedyn commented
Hi we have made few new changes, if you would like to keep the translation up to date, please do so.